In [1]:
l = [1, 2, 434, 4534]

In [2]:
l

[1, 2, 434, 4534]

---

In [4]:
import numpy as np

In [6]:
ar = np.array(l)

In [7]:
ar

array([   1,    2,  434, 4534])

---

In [9]:
arr = np.array([2, 4, 'ankit', 2.5, True])

In [10]:
arr

array(['2', '4', 'ankit', '2.5', 'True'], dtype='<U21')

In [11]:
l.sort()

In [12]:
l

[1, 2, 434, 4534]

In [13]:
l.pop()

4534

In [14]:
l

[1, 2, 434]

In [15]:
ar.mean()

1242.75

---

In [16]:
ar

array([   1,    2,  434, 4534])

In [17]:
ar[2:5]

array([ 434, 4534])

In [18]:
ar

array([   1,    2,  434, 4534])

In [19]:
b = ar[2:4]

In [20]:
b

array([ 434, 4534])

In [21]:
b[0]

434

In [27]:
b.view

<function ndarray.view>

---

In [22]:
l

[1, 2, 434]

In [23]:
l[0:1]

[1]

In [24]:
l

[1, 2, 434]

In [25]:
c = l[1:]

In [26]:
c

[2, 434]

---

In [28]:
ages = np.array([20, 21, 25, 26, 24, 30, 28])

In [29]:
ages

array([20, 21, 25, 26, 24, 30, 28])

In [30]:
ages.sort()

In [31]:
ages

array([20, 21, 24, 25, 26, 28, 30])

In [32]:
_ages = ages[2:5]

In [33]:
_ages

array([24, 25, 26])

In [34]:
_ages[0]

24

In [35]:
_ages

array([24, 25, 26])

In [37]:
_ages[:] = [38, 39, 40]

In [38]:
_ages

array([38, 39, 40])

In [39]:
ages

array([20, 21, 38, 39, 40, 28, 30])

In [48]:
_ages_copy = ages.copy()

In [49]:
_ages_copy

array([20, 21, 38, 39, 40, 28, 30])

In [50]:
_ages_copy[0] = 1

In [51]:
_ages_copy

array([ 1, 21, 38, 39, 40, 28, 30])

In [52]:
ages

array([20, 21, 38, 39, 40, 28, 30])

---

In [40]:
l

[1, 2, 434]

In [41]:
la = l[1:]

In [42]:
la

[2, 434]

In [43]:
la[:] = [11, 12]

In [44]:
la

[11, 12]

In [45]:
l

[1, 2, 434]